version: '3.3'

services:
  nginx:
    image: nginx:1.19.6
    container_name: skale_nginx
    network_mode: host
    depends_on:
      - watchdog
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  watchdog:
    container_name: skale_watchdog
    image: "skale-watchdog:local"
    build:
      context: "."
      dockerfile: Dockerfile
    network_mode: host
    cpus: "0.5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_APP_PORT: 3010
      FLASK_APP_HOST: "127.0.0.1"
      FLASK_DEBUG_MODE: "False"
