version: '3.3'

services:
  nginx:
    image: nginx:1.13.7
    container_name: skale_nginx
    depends_on:
      - watchdog
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3009:3009

  watchdog:
    container_name: skale_watchdog
    image: skalenetwork/watchdog:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_APP_PORT: 3010
      FLASK_APP_HOST: "127.0.0.1"
      FLASK_DEBUG_MODE: "False"